### ISSUE TITLE
Sound Muted

### ISSUE THREAD

**Issue by HurricanKai** [calledude/SpotifyVolumeExtension#3]
When having the Windows sound at 2 (or 1) and Lowering the Volume of windows, Windows goes Muted and the Application can't Pick it up

Easily worked around by setting the Volume to anything else.

**Comment by calledude** [comment]
I'm pretty sure this is just a graphical glitch on Windows part, which I can't really control. The sound can't be muted while the program and spotify is running.

**Comment by calledude** [comment]
Nevermind, I see it now. It won't change the spotify-volume if the system volume is less than 2. I'll check it out.
